# ==========================================
# BENCHMARK CONFIGURATION
# ==========================================

# Base directory where all benchmark outputs (plots, metrics) will be saved
results_base_dir: './benchmark/results'
#results_predictions_dir: './benchmark/results/predictions'

datasets:
  toy:
    type: 'toy'
    shape_name: 'None'
    origin_dir: './datasets/toy_example'
    trajectory_number: 7
    test_id: 0
    r2_letter: "J"
    s2_letter: "C"
    # Preprocessing params for benchmark generation
    interpolation_points: 500
    min_window: 80
    max_window: 480
    samples_per_path: 250
    time_steps: 100
    # Benchmark-specific save paths
    benchmark_dir: './benchmark/data/toy'
    gt_data: './benchmark/data/toy/ground_truth.pt'

  lasa:
    type: 'lasa'
    shape_name: '{shape}'
    origin_dir: './datasets/lasa'
    origin_file: '{shape}_UQ.mat'
    trajectory_number: 7
    # Preprocessing params for benchmark generation
    min_window: 180
    max_window: 980
    samples_per_path: 250
    time_steps: 100
    # Benchmark-specific save paths (dynamically replaces {shape})
    benchmark_dir: './benchmark/data/lasa_{shape}'
    gt_data: './benchmark/data/lasa_{shape}/ground_truth.pt'

frameworks:
  graph:
    axis_points: 100
    graph_size: 100
    toy:
      latent_frame: 10
    lasa:
      latent_frame: 15
  stochman:
    axis_points: 100
    toy:
      latent_frame: 10
    lasa:
      latent_frame: 15
  node:
    axis_points: 100
    toy:
      latent_frame: 10
      latent_dim: 2
      hidden_dim: 256
      model_dir: './models/node/toy_example'
      model_name: 'NODE_{shape}RiemannianMSE_EGI'
    lasa:
      latent_frame: 15
      model_dir: './models/node/lasa'
      model_name: 'NODE_{shape}RiemannianMSE_EGI'
      N:
        latent_dim: 2
        hidden_dim: 512
      Angle:
        latent_dim: 2
        hidden_dim: 256
      P:
        latent_dim: 2
        hidden_dim: 512
      Leaf_1:
        latent_dim: 2
        hidden_dim: 512

